[workspace]
resolver = "2"
members = [
    "olpc-cjson",
    "tough",
    "tough-ssm",
    "tough-kms",
    "tuftool",
]

[workspace.dependencies]
assert_cmd = "2.2"
async-recursion = "1"
async-trait = "0.1"
aws-config = { version = "1", default-features = false, features = ["credentials-process", "default-https-client", "rt-tokio"] }
aws-lc-rs = "1"
aws-sdk-kms = { version = "1", default-features = false, features = ["behavior-version-latest", "default-https-client", "rt-tokio"] }
aws-sdk-ssm = { version = "1", default-features = false, features = ["behavior-version-latest", "default-https-client", "rt-tokio"] }
aws-smithy-runtime = "1"
aws-smithy-http = "0.64"
aws-smithy-http-client = { version = "1", features = ["rustls-aws-lc"] }
aws-smithy-types = "1"
base64 = "0.23"
bytes = "1"
clap = { version = "4", features = ["derive"] }
dyn-clone = "1"
futures = "0.3"
futures-core = "0.3"
globset = "0.4"
hex = "0.4"
hex-literal = "1.1"
http = "1"
httptest = "0.16"
jiff = { version = "0.2", features = ["serde"] }
log = "0.4"
maplit = "1"
pem = "4"
percent-encoding = "2"
rayon = "1"
reqwest = { version = "0.13", default-features = false }
rustls = "0.23"
rustls-native-certs = "0.8"
rustls-platform-verifier = "0.7"
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
serde_plain = "1"
simplelog = "0.12"
snafu = "0.9"
tempfile = "3"
tokio = "1"
tokio-test = "0.4"
tokio-util = { version = "0.7", features = ["io"] }
typed-path = "0.12"
unicode-normalization = "0.1"
# pinned due to aws-lc-rs locked to this version
# https://github.com/aws/aws-lc-rs/issues/468
untrusted = "=0.7.1"
url = "2"
walkdir = "2"
