[package]
name = "tuftool"
version = "0.17.0"
description = "Utility for creating and signing The Update Framework (TUF) repositories"
authors = ["iliana destroyer of worlds <iweller@amazon.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/awslabs/tough"
keywords = ["tuf", "update", "repository"]
edition = "2018"

[features]
integ = []
default = ["aws-sdk-rust"]
aws-sdk-rust = ["aws-sdk-rust-rustls"]
# This feature is for backward compatibility but has no effect.
aws-sdk-rust-rustls = []
fips = ["tough/fips", "rustls/fips"]

[dependencies]
aws-config.workspace = true
aws-lc-rs.workspace = true
aws-sdk-kms.workspace = true
aws-sdk-ssm.workspace = true
base64.workspace = true
clap.workspace = true
futures.workspace = true
hex.workspace = true
jiff.workspace = true
log.workspace = true
maplit.workspace = true
olpc-cjson = { version = "0.1", path = "../olpc-cjson" }
rayon.workspace = true
reqwest = { workspace = true, default-features = false, features = ["rustls-no-provider", "stream"] }
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
simplelog.workspace = true
snafu = { workspace = true, features = ["backtraces-impl-backtrace-crate"] }
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
tough = { version = "0.24", path = "../tough", features = ["http"] }
tough-kms = { version = "0.16", path = "../tough-kms" }
tough-ssm = { version = "0.19", path = "../tough-ssm" }
url.workspace = true
walkdir.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
futures.workspace = true
futures-core.workspace = true
httptest.workspace = true
